module.exports = [
    `a very fierce White Tiger that is ready to protect its owner from all dangers.`,
    `a Striped Tiger with extraordinary strength as a faithful guardian in every step of life.`,
    `a Golden Dragon that brings endless luck and wealth throughout life.`,
    `a Magical Monkey that is clever and agile, always accompanying in facing all life's obstacles.`,
    `a Snake spirit that can ward off all evil intentions and supernatural attacks that threaten.`,
    `a Guardian Angel who always gives blessings, peace, and protection at all times.`,
    `a Shadowless Warrior who is invisible to enemies and always present in difficult times.`,
    `the Queen of the South Sea who gives extraordinary charm and strong attraction to anyone who sees her.`,
    `a Magical Eagle that always flies high, watching over and guarding from the sky.`,
    `a magical Shaman who becomes a spiritual advisor, guiding in every important decision.`,
    `a small Tuyul that always helps smooth its owner's fortune without others knowing.`,
    `a big, hairy Genderuwo ready to scare enemies with evil intentions.`,
    `a Jin Ifrit from the fire group that is strong and can burn all evil intentions that threaten.`,
    `a Magical Tiger spirit that guards the family lineage for generations.`,
    `a Tree Guardian Jin that faithfully guards property and the safety of its owner.`,
    `a Black Shadow figure that always lurks and drives away evil spirits that approach.`,
    `a Jin Descendant of a King who has extraordinary authority and brings great luck.`,
    `a Wolf spirit that is clever, fast, and fierce in guarding and hunting enemies.`,
    `a Supernatural Being Guarding Ancestral Heritage that is always present when its owner is in difficulty.`,
    `a Sea Dragon spirit that guards from all dangers on land and sea.`,
    `a white Kuntilanak that instead becomes a protector from supernatural attacks and black magic.`,
    `a Magical Sword Warrior who is always ready to slash enemies and invisible disturbances.`,
    `a White Guardian Monkey that is agile and has extraordinary supernatural strength.`,
    `a magical Pocong that instead becomes an intermediary for luck and fortune for its owner.`,
    `a White Crocodile spirit that guards rivers and all watery places, protecting from water disasters.`,
    `a big White Eagle that always watches from the air and brings good news.`,
    `the Goddess Guardian of the Door of Fortune who opens the way for fortune from various directions without stopping.`,
    `a Black Tiger spirit that is fierce and only submits to its owner.`,
    `an Ancestral Spirit that always guides the path of life and gives invisible protection.`,
    `a magical Elephant spirit that brings luck, strength, and glory.`,
    `an old Priest guarding wisdom and giving guidance in difficult times.`,
    `a Supernatural Troop Jin that is ready to attack anyone who dares to disturb its owner.`,
    `a Guardian of the magical Keris that guards the safety and adds to the authority of its owner.`,
    `a Green Snake spirit that guards treasure and protects from black magic and witchcraft.`,
    `a red Kuntilanak that instead brings luck in the world of business and trade.`,
    `a Black Cat spirit that is clever and able to change the fate of its owner.`,
    `a Supernatural King guarding the astral kingdom that gives supernatural power to its owner.`,
    `a Black Horse spirit that is able to take its owner anywhere in the astral world.`,
    `the God of Fortune who always accompanies and showers wealth without stopping.`,
    `a White Deer spirit that brings tranquility, luck, and peace of life.`,
    `the Queen of Setaman Flowers that is fragrant and guards the charm and luck of its owner.`,
    `a Black Eagle spirit that flies high, bringing good news and warding off danger.`,
    `the Guardian of the Supernatural Realm Gate that ensures the safety of its owner from astral attacks.`,
    `a Red Snake spirit that guards wealth and protects from all evils of black magic.`,
    `a Supernatural Soldier of the Majapahit kingdom ready to fight for the safety of its owner.`,
    `a Black Monkey spirit that is agile and able to subtly steal enemy secrets.`,
    `a Supernatural Princess from Mount Lawu who gives supernatural powers and luck in trade.`,
    `an Owl spirit that guards the night and is always alert from enemy attacks.`,
    `the Satria Piningit who is prophesied to bring great glory and luck.`
];