module.exports = [
  "Did you know? Honey is the only food that never spoils.",
  "Did you know? Octopuses have three hearts and blue blood.",
  "Did you know? Giraffes only need about 30 minutes of sleep per day.",
  "Did you know? Indonesia has more than 17,000 islands.",
  "Did you know? The highest waterfall in the world is Angel Falls in Venezuela.",
  "Did you know? Cats can't taste sweetness.",
  "Did you know? Humans share about 60% of their DNA with bananas.",
  "Did you know? Sharks are the only fish that can blink with both eyes.",
  "Did you know? Hummingbirds are the only birds that can fly backwards.",
  "Did you know? The planet Saturn could float in water because it's less dense than water.",
  "Did you know? The human heart beats about 100,000 times per day.",
  "Did you know? Earth rotates at about 1,670 km/h at the equator.",
  "Did you know? Emojis first appeared in Japan in 1999.",
  "Did you know? The Dead Sea has 9 times higher salt content than regular oceans.",
  "Did you know? Ants can lift 50 times their body weight.",
  "Did you know? Hot water can freeze faster than cold water, known as the Mpemba effect.",
  "Did you know? Rhinos have skin 5 cm thick but are sensitive to insect bites.",
  "Did you know? Bees must visit about 2 million flowers to produce one pound of honey.",
  "Did you know? Human bones are five times stronger than steel of the same weight.",
  "Did you know? The light bulb was invented by Thomas Edison in 1879.",
  "Did you know? Dolphins sleep with one eye open.",
  "Did you know? The speed of a human sneeze can reach 160 km/h.",
  "Did you know? 80% of the world's volcanoes are in the Pacific Ring of Fire.",
  "Did you know? The planet Venus rotates in the opposite direction of other planets.",
  "Did you know? Zebras actually have black skin with white stripes.",
  "Did you know? Rhino horns are made of keratin, the same as human hair and nails.",
  "Did you know? Ostriches have eyes larger than their brains.",
  "Did you know? Human teeth are as hard as gemstones.",
  "Did you know? Crocodiles can live without eating for over a year.",
  "Did you know? Mount Everest grows about 4 mm per year.",
  "Did you know? One teaspoon of soil contains more microorganisms than the number of humans on Earth.",
  "Did you know? The human brain can store 2.5 petabytes of information, equivalent to 3 million hours of video.",
  "Did you know? Crickets can tell temperature by their chirping sound.",
  "Did you know? Human eyeballs remain the same size from birth, but the nose and ears keep growing.",
  "Did you know? The Titanic took over 2 hours to sink.",
  "Did you know? Elephants can detect vibrations through their feet from kilometers away.",
  "Did you know? The Sun's diameter is 109 times larger than Earth's.",
  "Did you know? The blue whale is the largest animal to have ever lived on Earth.",
  "Did you know? The Great Wall of China is not visible from space with the naked eye; that's a myth.",
  "Did you know? Every human has a unique body odor except identical twins.",
  "Did you know? Human blood vessels could circle the Earth 2.5 times if connected.",
  "Did you know? Butterflies can smell from a distance of more than 2 km.",
  "Did you know? The average human walks the equivalent of 5 times around the Earth in their lifetime.",
  "Did you know? Dragonflies have existed since the time of dinosaurs.",
  "Did you know? Deer don't have a gallbladder.",
  "Did you know? The human brain uses 20% of the body's energy even though it only weighs 2% of the body.",
  "Did you know? At the North Pole, the sun can rise for 6 months without setting.",
  "Did you know? Bees can recognize human faces.",
  "Did you know? Spicy food triggers endorphins, making it addictive.",
  "Did you know? The human tongue print is as unique as a fingerprint.",
  "Did you know? The Sahara Desert was once an ocean.",
  "Did you know? The largest fungus in the world weighs more than 400 tons.",
  "Did you know? The oldest tree in the world is over 5,000 years old.",
  "Did you know? Turtles can live over 150 years.",
  "Did you know? More than 70% of Earth's oxygen comes from the ocean.",
  "Did you know? In space, astronauts cannot sneeze.",
  "Did you know? Astronauts are 5 cm taller in space because there's no gravity.",
  "Did you know? Worms can have up to 10 hearts.",
  "Did you know? The human brain generates enough electricity to power a small light bulb.",
  "Did you know? Camels can drink 100 liters of water in one go.",
  "Did you know? Owls can rotate their heads up to 270 degrees.",
  "Did you know? Electricity was first discovered by Benjamin Franklin in 1752.",
  "Did you know? The longest recorded time a human has gone without sleep is 11 days.",
  "Did you know? Frozen seawater becomes ice that tastes fresh.",
  "Did you know? Basketball was originally made from a soccer ball.",
  "Did you know? The Moon is slowly moving away from Earth by about 3.8 cm per year.",
  "Did you know? The hottest temperature ever recorded on Earth is 56.7°C at Furnace Creek Ranch, Death Valley, USA.",
  "Did you know? Since 2011, more people have died from selfies than from shark attacks.",
  "Did you know? Cows have best friends and can get stressed when separated.",
  "Did you know? Coconut water can be used as a substitute for intravenous fluid.",
  "Did you know? Inuit people have more than 50 words to describe snow.",
  "Did you know? Bees wouldn't be able to fly if they followed human aerodynamics.",
  "Did you know? In Japan, there's the world's oldest hotel that has been operating since 705 AD.",
  "Did you know? The surface of Venus is hotter than Mercury even though it's farther from the sun.",
  "Did you know? The oldest language still in use today is Tamil.",
  "Did you know? We spend about 6 months of our lives just waiting at red lights.",
  "Did you know? One million seconds is 11 days, but one billion seconds is 31 years.",
  "Did you know? Our stomach produces a new layer of mucus every 2 weeks to avoid digesting itself.",
  "Did you know? There are more than 200 corpses left on Mount Everest, and they now serve as landmarks.",
  "Did you know? The electric guitar was first introduced in 1931.",
  "Did you know? Male penguins propose to females with a small stone.",
  "Did you know? The human nose can smell more than 1 trillion different scents."
];